name: Process YouTube Links from Issue

on:
  issues:
    types: [opened]

jobs:
  extract-and-transcribe:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract YouTube Links from Issue Body
      id: extract_links
      run: |
        # Extract YouTube URLs from issue body
        cat <<EOF > links.txt
        ${{ github.event.issue.body }}
        EOF
        echo "Extracted Links:"
        cat links.txt

    - name: Read Links
      id: read_links
      run: |
        links=$(cat links.txt)
        echo "::set-output name=links::${links}"

    # - name: Authenticate GitHub CLI
    #   env:
    #     GH_TOKEN: ${{ secrets.GH_TOKEN }}
    #   run: |
    #     echo $GH_TOKEN | gh auth login --with-token

    - name: Call Reusable Workflow for Each Link
      # env:
      #   GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        links="${{ steps.read_links.outputs.links }}"
        suffix="small"  # You can change this to get suffix dynamically if needed
        IFS=$'\n' read -rd '' -a link_array <<< "$links"
        for link in "${link_array[@]}"; do
          echo "Processing $link"
          gh workflow run .github/workflows/transcribe-youtube.yml --ref main --field youtube_url="$link" --field suffix="$suffix"
        done
