name: Process YouTube Links from Issue

on:
  issues:
    types: [opened]

jobs:
  extract-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract YouTube Links from Issue Body
      id: extract_links
      run: |
        # Extract YouTube URLs from issue body
        cat <<EOF > links.txt
        ${{ github.event.issue.body }}
        EOF
        echo "Extracted Links:"
        cat links.txt

    - name: Read Links
      id: read_links
      run: |
        links=$(cat links.txt | awk NF)
        echo "::set-output name=links::$(jq -R -s -c 'split("\n") | map(select(length > 0))' <<< "$links")"

  run-transcriptions:
    needs: extract-and-run
    strategy:
      matrix:
        link: ${{ fromJson(needs.extract-and-run.outputs.links) }}
    uses: ./.github/workflows/transcribe-youtube.yml
    with:
      youtube_url: ${{ matrix.link }}
      suffix: small
