name: Process YouTube Links from Issue

on:
  issues:
    types: [opened]

jobs:
  extract-and-run:
    runs-on: ubuntu-latest
    outputs: 
      links: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract YouTube Links from Issue Body
      id: extract_links
      run: |
        # Extract YouTube URLs from issue body
        cat <<EOF > links.txt
        ${{ github.event.issue.body }}
        EOF
        echo "Extracted Links:"
        cat links.txt
        awk 'NF' links.txt | jq -c -R -s 'split("\r\n") | map(select(length > 0))' > links.json

    - id: set-matrix
      run: |
        # Read links from JSON file
        cat links.json
        echo "matrix=$(cat links.json)" >> $GITHUB_OUTPUT

  run-transcriptions:
    needs: extract-and-run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        link: ${{ fromJson(needs.extract-and-run.outputs.links) }}
    steps:
    - name: Call Reusable Workflow for Each Link
      uses: ./.github/workflows/transcribe-youtube.yml
      with:
        youtube_url: ${{ matrix.link }}
        suffix: small
