name: transcribe-urls-from-issues

on:
  issues:
    types: [opened]

jobs:
  extract-and-run:
    runs-on: ubuntu-latest
    outputs: 
      links: ${{ steps.set-matrix.outputs.matrix }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Extract YouTube Links from Issue Body
      id: extract_links
      run: |
        # Extract YouTube URLs from issue body
        cat <<EOF > links.txt
        ${{ github.event.issue.body }}
        EOF
        echo "Extracted Links:"
        cat links.txt
        awk 'NF' links.txt | jq -c -R -s 'split("\r\n") | map(select(length > 0))' > links.json

    - id: set-matrix
      run: |
        # Read links from JSON file
        cat links.json
        echo "matrix=$(cat links.json)" >> $GITHUB_OUTPUT

  run-transcriptions:
    needs: extract-and-run
    strategy:
      matrix:
        link: ${{ fromJson(needs.extract-and-run.outputs.links) }}
    uses: ./.github/workflows/transcibe-url-with-title.yml
    with:
      youtube_url: ${{ matrix.link }}
      suffix: medium

  upload_artifacts:
    needs: run-transcriptions
    if: |
      !cancelled()
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: downloaded_artifacts

    - name: Commit and push artifacts
      run: |
        # Set up Git
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        
        # Copy artifacts to the repository directory
        cp -R downloaded_artifacts/* .
        
        # Add, commit, and push changes
        git add .
        git commit -m "Add transcribed artifacts"
        git push
