name: Transcript YouTube Video

on:
  workflow_dispatch:
    inputs:
      youtube_url:
        description: 'YouTube Video URL'
        required: true

jobs:
  youtube-2-video:
    name: Transcript English Video
    runs-on: ubuntu-latest
    container: xihajun/whisper-yt-cpu:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Download and Transcribe YouTube Video
      run: |
        # Download YouTube video
        mkdir youtube
        cd youtube
        youtube-dl -o 'youtube.mp4' '${{ github.event.inputs.youtube_url }}'

        # Convert video to wav
        ffmpeg -i youtube* -ac 1 -ar 16000 -f wav /tmp/youtube.wav
        ls -lh /tmp
        # Transcribe wav to text using whisper
        cd /app
        ./main -f /tmp/youtube.wav -ocsv -oj -otxt -osrt -of output
        # grep -oP '(?<=\[)\d{2}:\d{2}:\d{2}\.\d{3}(?= -->)|(?<=\]\s{3}).*' <<< "$(./main -f /tmp/youtube.wav -ocsv -oj -otxt -osrt -of output)" | sed 'N;s/\n/ /' | sed -E 's/(\[.*)\.\d{3}( -->.*)\.\d{3}(.*)/\1\2\3/' > output.extracted_text.txt


    - name: Upload Output Files
      uses: actions/upload-artifact@v3
      with:
        name: transcription-output
        path: /app/output.*
